### PR TITLE
Support Python 2.6

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Builds at https://travis-ci.org/jayvdb/globre/builds

**Comment by metagriffin** [comment]
i'm not a fan of python pre 2.7, when several key changes were made (i can't really remember what, but there were several that i depend on as a matter of course), which is why it is explicitly specified in all of my setup.py files.

i can only accept this PR if you are willing to commit to maintaining backward compatibility to 2.6 for any future changes made. are you willing?

**Comment by jayvdb** [comment]
Sure. I want to use this in my flake8-putty , which is a developer / build tool , so my tests will break and ill be keeping py26 supported as long as people are using it.

**Comment by jayvdb** [comment]
I also support py26 in Pywikibot, so ive seen nearly every quirk there is in it.

**Comment by metagriffin** [comment]
great, thanks!

**Pull request merged**
